name: Release Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Run Tests
        working-directory: .
        run: go test -v .

      - name: Run Benchmarks
        working-directory: .
        run: go test -bench=.